[package]
name = "pathfinder"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
anyhow = "1"
alloy = { version = "1.0.41", features = ["full", "dyn-abi", "json-abi", "signer-local", "reqwest-rustls-tls"] }
alloy-provider = "1.5.2"
alloy-providers = "0.0.0-reserved"
reqwest = "0.13.1"
url = "2.5.7"
chrono = "0.4.43"
futures = "0.3.31"
alloy-json-abi = "1.5.4"
alloy-contract = "1.6.1"
clickhouse = "0.13.3"
hex = "0.4.3"


[[bin]]
name = "test_scanners1"
path = "src/bin/test_scanners1.rs"

[[bin]]
name = "new"
path = "src/bin/new.rs"
